version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:14

jobs:
  build:
    executor: node-executor
    steps:
      - checkout

      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules

      - run:
          name: Build
          command: yarn build

  deploy:
    executor: node-executor
    steps:
      - checkout

      - run:
          name: Install AWS CLI
          command: |
            curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

      - run:
          name: Deploy to S3
          command: |
            aws configure set aws_access_key_id "AKIA6ICKIGUH6VDTTXOI"
            aws configure set aws_secret_access_key "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"
            aws configure set default.region "us-east-2"

            mkdir -p .build/

            aws s3 sync .build/ s3://aws-deploy-infinite

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
                - master

      - deploy:
          filters:
            branches:
              only:
                - main
                - master
          requires:
            - build
